env:
  node: true
  mocha: true
  es6: true
extends: 
  - eslint:recommended 
plugins: 
  - prettier
parser: 
  babel-eslint
parserOptions:
  sourceType: module
rules:
  arrow-body-style: [2, as-needed]
  arrow-spacing: 2
  camelcase: [2, properties: always]
  complexity: [2, 20]
  indent: [2, 2]
  max-depth: [2, 4]
  max-params: [2, 3]
  max-statements: [2, 15]
  max-nested-callbacks: [2, 3]
  max-len: [1, code: 200]
  no-alert: 2
  no-caller: 2
  no-console: 1
  no-empty-function: 2
  no-else-return: 2
  no-eval: 2
  no-extend-native: 2
  no-new-wrappers: 2
  no-script-url: 2
  no-throw-literal: 2
  no-void: 2
  no-with: 2
  no-trailing-spaces: 2
  no-duplicate-imports: 2
  no-useless-constructor: 2
  no-var: 2
  prefer-promise-reject-errors: 2
  prefer-rest-params: 2
  quotes: [2, single]
  require-await: 2
  semi: [2, always]